### ISSUE TITLE
Debounce email check / only check valid emails

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-auth#129]
Currently we flood the service with requests once the `x@y` form is reached, meaning one request for every character of the domain. We should debounce this request at a factor of ~300ms so we'll only get ~1 request for most typists.

This would also prevent the "sorry we couldn't find your email check" which is gross and obviously wrong/unhelpful when a person is still typing.

**Comment by awolfe76** [comment]
Another possibility here would be to do some front-end validation so that we don't even make the API calls until it's a valid email address. We'd need to be sure that we're using the same check as the back-end to avoid any confusion (valid on the front-end, invalid on the back-end).

And the message for invalid, `x@y`, could be updated to say that it's invalid instead of "we can't find it". It would be more clear this way.

**Comment by wpears** [comment]
Yeah, I think we could be a little smarter about the email check (thus the second half of this issue title), but doing the check identically to the backend would require having the *data* in the front-end, which I don't think we want to do.

Pretty quick win would be to first require a `.` in the domain, then also debounce. That would reduce almost all unnecessary requests.

**Comment by wpears** [comment]
Closed by #131
