### ISSUE TITLE
Update link expiration time

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-auth#132]
Update the link expiration in keycloak from 5 minutes to 1 hour. While discussing w/ #102, #103 and #104 with @awolfe76, investigated the expiration times on other gov systems and one hour is standard. 

Will require updating the email messages to reflect the one hour expiration.

**Comment by hkeeler** [comment]
I think we're dealing with two separate timeout settings here:

| Setting | Currently | Description |
|---|---|---|
| Login action timeout | 5 min. | Max time a user has to complete login related actions like update password or configure totp.  This is recommended to be relatively long.  5 minutes or more. |
| User-Initiated Action Lifespan | 5 min. | Max time before an action permit sent by a user (e.g. forgot password e-mail) is expired.  This is recommended to be short because it is expected that the user would react to self-created actions quickly. |

I've confirmed that the _account registration_ and _forgot password_ both use the _User-Initiated Action Lifespan_.  It doesn't _seem_ like _Login action timeout_ shows up in any of the confirmation emails we're using, but I'm going to test a bit more.  It could end up in there for some admin-initiated actions.

Do we want to set both to 60 minutes?

As for the above requirement:
>Will require updating the email messages to reflect the one hour expiration.

This shouldn't be necessary so long as we're OK with the message _This link will expire within **60 minutes**_ instead of something like _This link will expire within **1 hour**_.

I propose we keep it as is.

@keileyo, thoughts?

**Comment by awolfe76** [comment]
👍  to keeping it as ... at least for now.

**Comment by keileyo** [comment]
yep sounds good to me.

**Comment by hkeeler** [comment]
Great.  Should have a PR up for this shortly.
