### ISSUE TITLE
Multiple institutions selected by default in registration

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#159]
When I last saw multiple institutions pop up in registration, they had to be individually selected to be added. Since all the applicable institutions should be added at once, and not as-needed, I think all the checkboxes should be pre-selected (if they aren't already). Opt-out instead of opt-in.

**Comment by keileyo** [comment]
Agree, a "nice to have" would be some content letting the multi institution user know that they need to select all institutions that they plan to file for AT the time of signing up for an account because they can't come back later add the second or third institution. I know in the grand scheme of things that multiple institution filers are a small population, so it doesn't necessarily make sense to crowd the institutions page with instructions for multiple filers. What might make sense as an enhancement in the future would be some kind of modal for multi-institution filers (not sure how feasible this is) that pops up when they select "Register" confirming that they have selected all institutions that they will file for. 

Our very small sample size of multi institution filers in user testing (1) said that they would have selected only the institution that they planned to file for in that particular filing.

**Comment by awolfe76** [comment]
@designlanguage @keileyo @wpears - in the last sprint planning we talked about having __NO__ institutions selected, so the default would always be nothing selected. The point being that even though the domain matches, they may not need (or should not have) access so we shouldn't default it that way.

But, we should update the messaging here to make it more helpful so people are sure to select all the institutions they need to file for.

Any thoughts on a good way to message this?

#### Current message prior to entering email address

"To register as a filer for more than one institution, you may select multiple institutions from the list of available institutions based on your email domain. If one or more institutions is not available in the list based on your email domain, contact hmdahelp@cfpb.gov for assistance with registering for the additional institution(s)."

#### After email is entered

There is no message at this point, only the list of institutions is displayed.
