### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#37]
_Just to remember for later._

After seeing what #33 gets us we can see if its worth investigating more customization to the error messages.

**Comment by hkeeler** [comment]
@awolfe76, I've added `messages/messages_en.properties` as part of #38.  This can be used to add new error messages, or override exiting ones.

Which error messages were you thinking of when you created this issue?

**Comment by hkeeler** [comment]
We should definitely do something about the generic _something went wrong_ error:

<img width="611" alt="screen shot 2016-12-08 at 6 59 16 pm" src="https://cloud.githubusercontent.com/assets/4269085/21032612/95ecf7d0-bd78-11e6-9a84-1bb8856f838c.png">

**Comment by awolfe76** [comment]
Is that from a session timeout?

**Comment by awolfe76** [comment]
Heres another one:
![stale](https://cloud.githubusercontent.com/assets/2932572/21059957/1956d04c-be13-11e6-8412-2f626d359918.png)

**Comment by hkeeler** [comment]
Looks like these both come from [`theme/base/login/messages/messages_en.properties`](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/messages/messages_en.properties).

>Is that from a session timeout?

Sort of.  I think it is a bit more generic than that.  It's what happens when you have an _invalid code_, which _could_ be due to the associated session having expired, but could also be that the OIDC `code` provided is all-together bogus.  There are probably several scenarios this could occur.

In this particular case, we should probably put a link back to our app within this error message.  Without that, you're kinda stuck.

>The link you clicked is a old stale link...

I haven't seen this one before.  Yeah, we'd probably want to reword that one as well.

**Comment by awolfe76** [comment]
> In this particular case, we should probably put a link back to our app within this error message. Without that, you're kinda stuck.

👍  - i've seen this one a few times and yeah, its odd to get out of that. Would be nice to try to prevent it, longer session and whatever else.

**Comment by hkeeler** [comment]
Created https://github.com/cfpb/hmda-platform-auth/issues/40 to resolve the _invalid code_ deadend.

**Comment by hkeeler** [comment]
I'm closing this one out.  At this point we've fixed the dead end issue, and we have #39 for reviewing all of the error messages.
