### ISSUE TITLE
Registration password updates

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-auth#88]
Suggested updates to the registration / creation of password experience:

1) Suggest including a password progress bar during the login to ensure that all of the password strength conditions are met when the user is registering. 

~~2) Include a message next to the “confirm password” field that either confirms (think green check & passwords match message) or lets users know that the passwords don’t match.~~ (See #113)

**Comment by hkeeler** [comment]
I think we can make this happen.  No. 2 seems pretty straightforward.  I think that's just a matter of some frontend code comparing those two fields.

No. 1 is a little trickier.  Keycloak doesn't expose an API to access the password policy from the frontend.  However, we could extract the settings for those rules into some other file (ex: [`themes/hmda/login/theme.properties`](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/themes/hmda/login/theme.properties)), making them available to registration page ([`themes/hmda/login/register.ftl`](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/themes/hmda/login/register.ftl)), and then do a find/replace in [`import/hmda-realm.json:passwordPolicy`](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/import/hmda-realm.json#L208) at startup.  There'd be a bit of JS work to implement these rules, but I _think_ they'd be pretty straightforward.

Also, this would not work for the `passwordHistory` rule since that would require a call to the backend.  But we likely could implement `upperCase`, `lowerCase`, `digits`, `specialChars`, `length` and `notUsername`.

@awolfe76, thoughts?

**Comment by awolfe76** [comment]
Splitting this into 2 issues ... see #113

**Comment by hkeeler** [comment]
Issue https://github.com/cfpb/hmda-platform-auth/issues/120 is related to No. 1 mentioned above.  We could close this issue out, and use that one if that's the direction we want to go.

**Comment by awolfe76** [comment]
Yep, closing. We can use #120.
